Traceback (most recent call last):
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/client.py", line 526, in async_execute
    await self.async_execute_cell(
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/dsevero/miniconda3/envs/dsc4ml/lib/python3.8/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ρ = 0.8
μ = [0, 0]
σx = 1
σy = 1
Σ = [[     σx, ρ*σx*σy],
     [ρ*σx*σy,      σy]]
X, Y = npr.multivariate_normal(μ, Σ, size=1_000).T

# no side info
b_space = np.linspace(X.min(), X.max(), 100)
avg_01_loss = [((X > Y) != (X > b)).mean() for b in b_space]
hits_at_0 = (X > Y) == (X > 0)

plt.subplot(1, 2, 1)
plt.title('0-1 loss for fixed rule $X > b$')
plt.plot(b_space, avg_01_loss, 'o--')
plt.ylabel('loss value')
plt.xlabel('$b$')

plt.subplot(1, 2, 2)
plt.scatter(X, Y, alpha=0.1, c=hits_at_0)
plt.plot(*(2*[[X.min(), X.max()]]))
plt.ylabel('$Y$')
plt.xlabel('$X$')
plt.vlines(0, Y.min(), Y.max(), colors='gray')

from myst_nb import glue
glue("fig1", plt.gcf(), display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-99dd2140ab4c>[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m Σ = [[     σx, ρ*σx*σy],
[1;32m      6[0m      [ρ*σx*σy,      σy]]
[0;32m----> 7[0;31m [0mX[0m[0;34m,[0m [0mY[0m [0;34m=[0m [0mnpr[0m[0;34m.[0m[0mmultivariate_normal[0m[0;34m([0m[0mμ[0m[0;34m,[0m [0mΣ[0m[0;34m,[0m [0msize[0m[0;34m=[0m[0;36m1_000[0m[0;34m)[0m[0;34m.[0m[0mT[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;31m# no side info[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'npr' is not defined
NameError: name 'npr' is not defined

